// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Asteroids+",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Asteroids+",
            targets: ["AppModule"],
            bundleIdentifier: "com.choiysapple.AsteroidPlus",
            teamIdentifier: "ZW6466CHF4",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Sound/WaveStart.wav"),
                .copy("Sound/ShipHit.wav"),
                .copy("Sound/LifeUp.wav"),
                .copy("Sound/Fire.wav"),
                .copy("Sound/BulletUp.wav"),
                .copy("Sound/AsteroidHit.wav")
            ]
        )
    ]
)